import { type NextPage } from "next";
import Head from "next/head";
import { Input } from "~/component/input";
import { FormGroup } from "./FormGroup";

const GeneratePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center ">
        <form className="flex flex-col gap-4">
          <FormGroup>
            <label>Prompt</label>
            <Input></Input>
          </FormGroup>
          <button className="after: rounded bg-blue-400 px-4 py-2 hover:bg-blue-500">
            Submit
          </button>
        </form>
      </main>
    </>
  );
};

export default GeneratePage;
